hotwire_django_app/hotwire_django_app/stimulus_basics/urls.py
from django.urls import path
from .views import counter_view

app_name = 'stimulus-basic'

urlpatterns = [
    path('counter/', counter_view, name='counter'),
]

hotwire_django_app/hotwire_django_app/turbo_drive/urls.py
from django.urls import path
from .views import create_view, list_view

app_name = 'turbo-drive'

urlpatterns = [
    path('list/', list_view, name='task-list'),               
    path('create/', create_view, name='task-create'),
]

hotwire_django_app/hotwire_django_app/turbo_framez/urls.py
from django.urls import path
from .views import index_view, list_view, create_view, update_view, delete_view, detail_view

app_name = 'turbo-frame'

urlpatterns = [
    path('', index_view, name='index'),   
    path('list/', list_view, name='task-list'),
    path('create/', create_view, name='task-create'),
    path('<int:pk>/', detail_view, name='task-detail'),
    path('<int:pk>/update/', update_view, name='task-update'),
    path('<int:pk>/delete/', delete_view, name='task-delete'),
]

hotwire_django_app/hotwire_django_app/urls.py
from django.contrib import admin
from django.urls import path, include              
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html")),
    path('turbo-drive/', include('hotwire_django_app.turbo_drive.urls')),
    path('turbo-frame/', include('hotwire_django_app.turbo_framez.urls')),
    path('stimulus-basic/', include('hotwire_django_app.stimulus_basics.urls')),            
    path('admin/', admin.site.urls),
]

hotwire_django_app/hotwire_django_app/stimulus_basics/models.py
from django.db import models

# Create your models here.

hotwire_django_app/hotwire_django_app/tasks/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinLengthValidator


class Task(models.Model):
    title = models.CharField(
        max_length=250,
        validators=[MinLengthValidator(limit_value=3)]
    )
    due_date = models.DateField(default=timezone.now)

hotwire_django_app/hotwire_django_app/turbo_framez/models.py
from django.db import models

# Create your models here.

hotwire_django_app/hotwire_django_app/tasks/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ("title", "due_date")

hotwire_django_app/hotwire_django_app/stimulus_basics/views.py
from django.shortcuts import render


def counter_view(request):
    return render(request, 'stimulus_basic/counter.html')

hotwire_django_app/hotwire_django_app/tasks/views.py
from django.shortcuts import render

# Create your views here.

hotwire_django_app/hotwire_django_app/turbo_drive/views.py
from django.shortcuts import render, redirect

from hotwire_django_app.tasks.forms import TaskForm
from hotwire_django_app.tasks.models import Task
from django.urls import  reverse
from django.contrib import messages

import http


def list_view(request):
    object_list = Task.objects.all().order_by('-pk')

    context = {
        "object_list": object_list,
    }

    return render(request, 'turbo_drive/list.html', context)


def create_view(request):
    import time
    time.sleep(1)
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()

            messages.success(request, 'Task created successfully')
            return redirect(reverse('turbo-drive:task-list'))

        status = http.HTTPStatus.UNPROCESSABLE_ENTITY           
    else:
        status = http.HTTPStatus.OK           
        form = TaskForm()

    return render(request, 'turbo_drive/create.html', {'form': form}, status=status)    # new

hotwire_django_app/hotwire_django_app/turbo_framez/views.py
import http

from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages

from hotwire_django_app.tasks.models import Task
from hotwire_django_app.tasks.forms import TaskForm
from django.http import HttpResponse
from turbo_response import TurboFrame

def index_view(request):
    return render(request, 'turbo_framez/index.html')


def list_view(request):
    object_list = Task.objects.all().order_by('-pk')

    context = {
        "object_list": object_list,
    }

    return render(request, 'turbo_framez/list_page.html', context)


def create_view(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            instance = form.save()

            messages.success(request, 'Task created successfully')
            if request.turbo.frame:
                # if the request comes within Turbo Frame
                response = TurboFrame(
                    request.turbo.frame
                ).template('turbo_framez/message.html', {}).response(request)
                return response
            else:
                return redirect(reverse('turbo-frame:task-detail', kwargs={'pk': instance.pk}))

        status = http.HTTPStatus.UNPROCESSABLE_ENTITY
    else:
        status = http.HTTPStatus.OK
        form = TaskForm()

    return render(request, 'turbo_framez/create_page.html', {'form': form}, status=status)


def update_view(request, pk):
    instance = get_object_or_404(Task, pk=pk)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()

            if request.turbo.frame:
                # if request come from Turbo Frame
                return redirect(reverse('turbo-frame:task-detail', kwargs={'pk': instance.pk}))
            else:
                # if request come from standard page
                messages.success(request, 'Task update successfully')
                return redirect(reverse('turbo-frame:task-detail', kwargs={'pk': instance.pk}))

        status = http.HTTPStatus.UNPROCESSABLE_ENTITY
    else:
        status = http.HTTPStatus.OK
        form = TaskForm(instance=instance)

    return render(request, 'turbo_framez/update_page.html', {'form': form}, status=status)


def delete_view(request, pk):
    instance = get_object_or_404(Task, pk=pk)
    if request.method == 'POST':
        instance.delete()

        if request.turbo.frame:
            # if request come from Turbo Frame
            response = TurboFrame(f"task-detail-{pk}").response('')
            return response
        else:
            # if request come from standard page
            messages.success(request, 'Task deleted successfully')
            return redirect('turbo-frame:task-list')

    return render(request, 'turbo_framez/delete_page.html', {'instance': instance})


def detail_view(request, pk):
    instance = get_object_or_404(Task, pk=pk)
    return render(request, 'turbo_framez/detail_page.html', {'instance': instance})

hotwire_django_app/hotwire_django_app/templates/index.html
{% load webpack_loader static %}

<!DOCTYPE html>
<html>
<head>
  <title>Index</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% stylesheet_pack 'turbo_drive' %}
  {% javascript_pack 'turbo_drive' attrs='defer' %}
</head>
<body>

<div class="jumbotron py-5">
  <div class="w-full max-w-7xl mx-auto px-4">
    <h1 class="text-4xl mb-4">Hello, world!</h1>
    <p class="mb-4">This is a template for a simple marketing or informational website. It includes a large callout called a
      jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>

    <p><a class="btn-blue mb-4" href="#" role="button">Learn more »</a></p>

    <div class="flex justify-center">
      <img src="{% static 'vendors/images/webpack.png' %}" />
    </div>
  </div>
</div>

</body>
</html>

hotwire_django_app/hotwire_django_app/templates/stimulus_basic/base.html
{% load webpack_loader static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  {% stylesheet_pack 'stimulus_basic' attrs='data-turbo-track="reload"'%}
  {% javascript_pack 'stimulus_basic' attrs='data-turbo-track="reload" defer' %}

</head>
<body>

{% include 'stimulus_basic/navbar.html' %}

{% block content %}
{% endblock content %}

</body>
</html>

hotwire_django_app/hotwire_django_app/templates/stimulus_basic/counter.html
{% extends "stimulus_basic/base.html" %}

{% block content %}

<div class="w-full max-w-7xl mx-auto px-4">

  <h1 class="text-4xl sm:text-6xl lg:text-7xl mb-6">Counter</h1>
  <button
  class="px-4 py-2 bg-blue-500 hover:bg-blue-700 text-white font-semibold rounded-lg"
  data-controller="counter"
  data-action="keydown->counter#increment"
  tabindex="0"
>Click me</button>
<!-- Update -->

  <h1 data-controller="counter" data-action="click->counter#increment" class="text-4xl sm:text-6xl lg:text-7xl mb-6"></h1>

  <div data-controller="counter" data-action="click->counter#increment" class="text-4xl"></div>

</div>

{% endblock %}

hotwire_django_app/hotwire_django_app/templates/stimulus_basic/navbar.html
<nav class="flex items-center justify-between flex-wrap bg-teal-500 p-6 mb-4">
  <div class="w-full">
    <a href="{% url 'stimulus-basic:counter' %}" class="inline-block mt-0 text-teal-200 hover:text-white mr-4">
      Counter
    </a>
  </div>
</nav>

hotwire_django_app/hotwire_django_app/templates/turbo_drive/base.html
{% load webpack_loader static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  {% stylesheet_pack 'turbo_drive' %}
  {% javascript_pack 'turbo_drive' attrs='defer' %}
</head>
<body>

{% include 'turbo_drive/navbar.html' %}   
{% block content %}
{% endblock content %}

</body>
</html>

hotwire_django_app/hotwire_django_app/templates/turbo_drive/create.html
{% extends "turbo_drive/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="w-full max-w-7xl mx-auto px-4">

  <form method="post">
    {% csrf_token %}

    {{ form|crispy }}

    <button type="submit" class="btn-blue">Submit</button>
  </form>

</div>

{% endblock %}

hotwire_django_app/hotwire_django_app/templates/turbo_drive/list.html
{% extends "turbo_drive/base.html" %}

{% block content %}

  <div class="w-full max-w-7xl mx-auto px-4">
    <h1 class="text-4xl sm:text-6xl lg:text-7xl mb-6">Task List</h1>
    <div class="md:w-2/3 bg-white rounded-lg border mb-4">
      <ul class="divide-y-2 divide-gray-100" id="task-list-ul">
        {% for instance in object_list %}
          <li class="p-3 flex items-center">
            {{ instance.due_date|date:"Y-m-d" }}: {{ instance.title }}
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>

{% endblock %}

hotwire_django_app/hotwire_django_app/templates/turbo_drive/navbar.html
<nav class="flex items-center justify-between flex-wrap bg-teal-500 p-6 mb-4">
  <div class="w-full">
    <a href="{% url 'turbo-drive:task-list' %}" class="inline-block mt-0 text-teal-200 hover:text-white mr-4">
      List
    </a>
    <a href="{% url 'turbo-drive:task-create' %}" class="inline-block mt-0 text-teal-200 hover:text-white mr-4">
      Create
    </a>
  </div>
</nav>

hotwire_django_app/hotwire_django_app/templates/turbo_framez/base.html
{% load webpack_loader static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  {% stylesheet_pack 'turbo_frame' attrs='data-turbo-track="reload"' %}
  {% javascript_pack 'turbo_frame' attrs='data-turbo-track="reload" defer' %}

</head>
<body>

{% include 'turbo_framez/navbar.html' %}

{% include 'turbo_framez/message.html' %}

{% block content %}
{% endblock content %}

</body>
</html>

hotwire_django_app/hotwire_django_app/templates/turbo_framez/create_page.html
{% extends "turbo_framez/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="w-full max-w-7xl mx-auto px-4">

  <h1 class="text-4xl sm:text-6xl lg:text-7xl mb-6">Create Task</h1>

  {% if request.turbo.frame == "task-create" %}
  <turbo-frame id="task-create">
    {% include 'turbo_framez/form/create.html' %}
  </turbo-frame>
   {% else %}
     {% include 'turbo_framez/form/create.html' %}
  {% endif %}

</div>

{% endblock %}

hotwire_django_app/hotwire_django_app/templates/turbo_framez/delete_page.html
{% extends "turbo_framez/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="w-full max-w-7xl mx-auto px-4">
  <h1 class="text-4xl sm:text-6xl lg:text-7xl mb-6">Delete Task</h1>

  {% if request.turbo.frame %}
    <turbo-frame id="{{ request.turbo.frame }}">
      {% include 'turbo_framez/form/delete.html' %}
    </turbo-frame>
  {% else %}
     {% include 'turbo_framez/form/delete.html' %}
  {% endif %}

</div>
{% endblock %}

hotwire_django_app/hotwire_django_app/templates/turbo_framez/detail_page.html
{% extends "turbo_framez/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="w-full max-w-7xl mx-auto px-4">
  <h1 class="text-4xl sm:text-6xl lg:text-7xl mb-6">Task Detail</h1>

  <div class="mb-3 p-3 border">
    {% include 'turbo_framez/task_detail.html' with instance=instance only %}
  </div>

  <div>
    <a href="{% url 'turbo-frame:task-list'%}" class="btn-blue">Go to list</a>
  </div>

</div>
{% endblock %}

hotwire_django_app/hotwire_django_app/templates/turbo_framez/form/create.html
{% load crispy_forms_tags %}

<form method="post" action="{% url 'turbo-frame:task-create' %}">
  {% csrf_token %}

  {{ form|crispy }}

  <button type="submit" class="btn-blue">Submit</button>
</form>

hotwire_django_app/hotwire_django_app/templates/turbo_framez/form/delete.html
{% load crispy_forms_tags %}

<form method="post" action="{% url 'turbo-frame:task-delete' instance.pk %}">
  {% csrf_token %}

  <div class="p-4 mb-4 text-sm text-red-700 bg-red-100 rounded-lg dark:bg-red-200 dark:text-red-800" role="alert">
    Are you sure you want to delete "{{ instance.title }}"?
  </div>

  {{ form|crispy }}

  <button type="submit" class="btn-blue">Submit</button>

  {% if request.turbo.frame %}
    <a href="{% url 'turbo-frame:task-detail' instance.pk %}" class="btn-red">Cancel</a>
  {% else %}
    <a href="{% url 'turbo-frame:task-list' %}" class="btn-red">Cancel</a>
  {% endif %}

</form>

hotwire_django_app/hotwire_django_app/templates/turbo_framez/form/update.html
{% load crispy_forms_tags %}

<form method="post" action="{% url 'turbo-frame:task-update' form.instance.pk %}">

  {% csrf_token %}

  {{ form|crispy }}

  <button type="submit" class="btn-blue">Submit</button>

  {% if request.turbo.frame %}
    <a href="{% url 'turbo-frame:task-detail' form.instance.pk %}" class="btn-red">Cancel</a>
  {% else %}
    <a href="{% url 'turbo-frame:task-list' %}" class="btn-red">Cancel</a>
  {% endif %}

</form>

hotwire_django_app/hotwire_django_app/templates/turbo_framez/index.html
{% extends "turbo_framez/base.html" %}

{% block content %}

  <div class="w-full max-w-7xl mx-auto px-4">

    <h1 class="text-4xl sm:text-6xl lg:text-7xl mb-6">Turbo Frame Index Page</h1>

  <div class="mb-4">
    <turbo-frame id="task-create" src="{% url 'turbo-frame:task-create' %}">
      Loading...
    </turbo-frame>
  </div>

  <turbo-frame id="task-list" src="{% url 'turbo-frame:task-list' %}">
    Loading...
  </turbo-frame>
  </div>

{% endblock %}

hotwire_django_app/hotwire_django_app/templates/turbo_framez/list_page.html
{% extends "turbo_framez/base.html" %}

{% block content %}

<div class="w-full max-w-7xl mx-auto px-4">
  <h1 class="text-4xl sm:text-6xl lg:text-7xl mb-6">Task List</h1>

  <turbo-frame id="task-list">
  <div class="md:w-2/3 bg-white rounded-lg border mb-4">
    <ul class="divide-y-2 divide-gray-100" id="task-list-ul">
      {% for instance in object_list %}
      <li class="p-3 flex items-center">

        {% include 'turbo_framez/task_detail.html' with instance=instance only %}

      </li>
      {% endfor %}
    </ul>
  </div>
</turbo-frame>

</div>

{% endblock %}

hotwire_django_app/hotwire_django_app/templates/turbo_framez/message.html
{% for message in messages %}
  {#  data-turbo-cache="false" will tell Turbo to not cache the element #}
  <div data-turbo-cache="false" class="p-4 mb-4 text-sm text-green-700 bg-green-100 rounded-lg dark:bg-green-200 dark:text-green-800" role="alert">
    {{ message|safe }}
  </div>
{% endfor %}

hotwire_django_app/hotwire_django_app/templates/turbo_framez/navbar.html
<nav class="flex items-center justify-between flex-wrap bg-teal-500 p-6 mb-4">
  <div class="w-full">
    <a href="{% url 'turbo-frame:task-list' %}" class="inline-block mt-0 text-teal-200 hover:text-white mr-4">
      List
    </a>
    <a href="{% url 'turbo-frame:task-create' %}" class="inline-block mt-0 text-teal-200 hover:text-white mr-4">
      Create
    </a>
    <a href="{% url 'turbo-frame:index' %}" class="inline-block mt-0 text-teal-200 hover:text-white mr-4">
      Turbo Frame Index
    </a>
  </div>
</nav>

hotwire_django_app/hotwire_django_app/templates/turbo_framez/task_detail.html
<turbo-frame id="task-detail-{{ instance.pk }}" class="flex-1">

<a class="btn-blue mr-3" href="{% url 'turbo-frame:task-update' instance.pk %}">
  Edit
</a>
<a class="btn-red mr-3" href="{% url 'turbo-frame:task-delete' instance.pk %}">
  Delete
</a>

{{ instance.due_date }}: {{ instance.title }}

</turbo-frame>

hotwire_django_app/hotwire_django_app/templates/turbo_framez/update_page.html
{% extends "turbo_framez/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="w-full max-w-7xl mx-auto px-4">

  <h1 class="text-4xl sm:text-6xl lg:text-7xl mb-6">Edit Task</h1>

  {% if request.turbo.frame %}
  <turbo-frame id="{{ request.turbo.frame }}">
    {% include 'turbo_framez/form/update.html' %}
  </turbo-frame>
  {% else %}
    {% include 'turbo_framez/form/update.html' %}
  {% endif %}

</div>

{% endblock %}